### ISSUE TITLE
Error while receiving via netlink: Operation not supported

### ISSUE THREAD

**Issue by caveguy** [seemoo-lab/owl#12]
hi, I run owl on ubuntu with cisco wusb600n,and then got an err, What is the problem? thanks.

sudo owl -i wlx00259ce04ceb
              .oOXWMMMMWXOx:
         .oOOOx:'''''''''''':OOOx:
      oXOo'      ........      ':OXx.
           .oOOO''''''''''OOOo.
        oXOo'                'oOO:
             :oOOOOXXXXOOOOo:.
          oXO:'            ':OXo
              .:xOXXXXXXOx:.
          .xXMMMMMMMMMMMMMMMMXx.
  'XWWWWWWMMMMMMMMMMMMMMMMMMMMMMWWWWWWX'
    oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo
     OMMMMMMWWMMMMMMMMMMMMMMWWWMMMMMO
    OMMWx'      'xWMMMMWx'      'oXMMO
   :MW:            oMMx            'WM:
   XM'    .xOOo.    :o     .xOOo.    WX
   WX    :MMMMMX          :MMMMMX    xW
   XW    'WMMMMX   .xx.   'WMMMWX    XX
   'Wx    'xWMx'   OMMO    'xWMx'   xM'
    'XX:           'XX'           :XX'
      'xXOx:..................:xXWx'
         'xXMMMMMMMMMMMMMMMMMMWO'

            Open Wireless Link

            https://owlink.org

17:35:25 ERROR: Error while receiving via netlink: Operation not supported
17:35:25 ERROR: Could not put device in monitor mode: wlx00259ce04ceb
17:35:25 ERROR: could not initialize core

**Comment by caveguy** [comment]
$ sudo ifconfig wlx00259ce04ceb down
$ sudo iwconfig wlx00259ce04ceb mode monitor
$ sudo owl -i wlx00259ce04ceb -N

**Comment by schmittner** [comment]
Your adapter does not support *active* monitor mode. This setup is likely not going to work well for you.

**Comment by pseigo** [comment]
I get the same issue on openSUSE 15.2.

```log
11:05:46 ERROR: Error while receiving via netlink: Operation not supported
11:05:46 ERROR: Could not put device in monitor mode: wlan0
11:05:46 ERROR: could not initialize core
```

I am able to set to monitor mode using iwconfig:

```txt
wlan0     IEEE 802.11  Mode:Monitor  Tx-Power=0 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
```

And start owl with `-N`:

```log
11:09:46 INFO : WLAN device: wlan0 (addr 32:d0:c2:4e:1b:92)
11:09:46 INFO : Host device: awdl0
```

But I am not able to find my iPhone on iOS 13.4 nor is it able to find me. I am using an [
Intel Dual Band Wireless-AC 8260](https://ark.intel.com/content/www/us/en/ark/products/86068/intel-dual-band-wireless-ac-8260.html).

@schmittner I wasn't able to find any information about "active" monitor mode online. How would one determine if their card supports the mode you have in mind?

**Comment by schmittner** [comment]
**Checking support for *active* monitor mode:** If you receive `owl`'s error message, your card does not support *active* monitor mode. You can also check via `iw`. If your card supports it, you should see a [flag called "*active*"](https://wireless.wiki.kernel.org/en/users/documentation/iw) under the card's capabilities.
https://github.com/seemoo-lab/owl/blob/011f418ecd0dfd02c19a96e8e9a892770a36f204/daemon/netutils.c#L224-L225

**Technical explanation what *active* monitor mode is and why it is necessary:** In regular monitor mode (the one that you set  with `iwconfig` or with `iw` without specifying any flags), the Wi-Fi card is completely passive. Active monitor mode means that the card will send Wi-Fi acknowledgments (on the link layer) for frames addressed to its MAC address. Without this acknowledgment, the sending station will assume that the transmission was not successful and retransmit up to 7 times before eventually giving up. Therefore, no meaningful communication will be possible between the two stations.

**Regarding the darn `-N` flag:** This is *only* to be used if you are using a chip supported by Nexmon (Nexmon's monitor mode is *active*) or otherwise know what you are doing. This is also the reason why the flag is *not* mentioned in the README. `-N` will also disable setting the proper Wi-Fi channel which is probably the reason why your devices are unable to see each other.

**Comment by eggbean** [comment]
I have the same problem, with a ThinkPad T480s with an Intel wireless card (nothing unusual). 

```
$ iw wlp61s0 info
Interface wlp61s0
        ifindex 3
        wdev 0x1
        addr a4:c3:f0:cb:bd:17
        ssid XXXXX
        type managed
        wiphy 0
        channel 44 (5220 MHz), width: 40 MHz, center1: 5230 MHz
        txpower 22.00 dBm
        multicast TXQ:
                qsz-byt qsz-pkt flows   drops   marks   overlmt hashcol tx-bytestx-packets
                0       0       0       0       0       0       0       0      0
```
So this Intel wireless card is not supported?

**Comment by kaihendry** [comment]
Damn! `netlink: Operation not supported` on a 03:00.0 Network controller: Intel Corporation Wi-Fi 6 AX200 (rev 1a)

**Comment by Tecon** [comment]
> Damn! `netlink: Operation not supported` on a 03:00.0 Network controller: Intel Corporation Wi-Fi 6 AX200 (rev 1a)

Neither do Intel  AC9560

    software interface modes (can always be added):
		 * AP/VLAN
		 * monitor
	valid interface combinations:
		 * #{ managed } <= 1, #{ AP, P2P-client, P2P-GO } <= 1, #{ P2P-device } <= 1,
		   total <= 3, #channels <= 2
	HT Capability overrides:
		 * MCS: ff ff ff ff ff ff ff ff ff ff
		 * maximum A-MSDU length
		 * supported channel width
		 * short GI for 40 MHz
		 * max A-MPDU length exponent
		 * min MPDU start spacing
	Device supports TX status socket option.
	Device supports HT-IBSS.
	Device supports SAE with AUTHENTICATE command
	Device supports low priority scan.
	Device supports scan flush.
	Device supports per-vif TX power setting
	P2P GO supports CT window setting
	P2P GO supports opportunistic powersave setting
	Driver supports full state transitions for AP/GO clients
	Driver supports a userspace MPM
	Driver/device bandwidth changes during BSS lifetime (AP/GO mode)
	Device adds DS IE to probe requests
	Device can update TPC Report IE
	Device supports static SMPS
	Device supports dynamic SMPS
	Device supports WMM-AC admission (TSPECs)
	Device supports configuring vdev MAC-addr on create.
	Device supports randomizing MAC-addr in scans.
	Device supports randomizing MAC-addr in sched scans.
	Device supports randomizing MAC-addr in net-detect scans.
	Supported extended features:
		* [ VHT_IBSS ]: VHT-IBSS
		* [ RRM ]: RRM
		* [ MU_MIMO_AIR_SNIFFER ]: MU-MIMO sniffer
		* [ SCAN_START_TIME ]: scan start timestamp
		* [ BSS_PARENT_TSF ]: BSS last beacon/probe TSF
		* [ SET_SCAN_DWELL ]: scan dwell setting
		* [ FILS_STA ]: STA FILS (Fast Initial Link Setup)
		* [ CONTROL_PORT_OVER_NL80211 ]: control port over nl80211
		* [ TXQS ]: FQ-CoDel-enabled intermediate TXQs
