### ISSUE TITLE
Nix: Install fails to find pcap

### ISSUE THREAD

**Issue by jackmac92** [seemoo-lab/owl#41]
I've installed the deps from the README but I'm still having some issues related to libpcap-dev.

How could I specify an include path to help cmake find it?
 
```
❯ cmake ..
CMake Error at daemon/CMakeLists.txt:19 (find_path):
  Could not find pcap_INCLUDE using the following files: pcap.h


-- Configuring incomplete, errors occurred!
See also "/tmp/tmp.4uTXHt7Ecd/owl/CMakeFiles/CMakeOutput.log".
❯ whereis pcap
pcap: /usr/include/pcap.h /usr/include/pcap /usr/share/man/man3/pcap.3pcap.gz
```

**Comment by schmittner** [comment]
That's curious as `/usr/include` should be a CMake default search path. What OS/CMake version are your running?
In any case, you can try to add the path explicitly by changing:
https://github.com/seemoo-lab/owl/blob/221c086d2a8f5249ccd8bf543b551771c1fc051a/daemon/CMakeLists.txt#L19
to
```cmake
find_path(pcap_INCLUDE pcap.h PATHS /usr/include REQUIRED)
```

**Comment by jackmac92** [comment]
Hmm must be because my `cmake` is installed via nix/home-manager. After ensuring that I use a cmake from `apt-get` I the build works!

I did try adding PATHS  errored on pcap_LIBRARY  ```CMake Error at daemon/CMakeLists.txt:20 (find_library):
  Could not find pcap_LIBRARY using the following names: pcap
```

**Comment by schmittner** [comment]
If you get that error message now means that CMake was able to find the PCAP include directory. But failed on the next line, possibly again due to a missing search path:
https://github.com/seemoo-lab/owl/blob/221c086d2a8f5249ccd8bf543b551771c1fc051a/daemon/CMakeLists.txt#L20
I don't know why Nix behaves this way, if you find a solution, let me know.
