### ISSUE TITLE
Will OWL ever have a release? Seeking to package...

### ISSUE THREAD

**Issue by notthewave** [seemoo-lab/owl#45]

**Comment by schmittner** [comment]
I don't plan to issue a specific release for packaging. My argument is that OWL has very specific hardware requirements and is not well tested. If people do not read the accompanying README, they are likely to have a bad time.

**Comment by jcgruenhage** [comment]
In the case of void-packages, we'd be shipping the readme with the package, and if you want we can also add an install message, that prompts people to read that documentation when the package is installed. Not having a released version makes packaging owl difficult, because of a policy to not ship unreleased software.

Would you be willing to tag a release please? I'd like to at least try out opendrop, and I'm also willing to package the thing, but not having the ability to properly integrate it and contribute that integration into void-packages discourages me a lot from putting the effort in.
